directories:
  output: release
  buildResources: resources
appId: com.primerecorder.app
productName: PRIMErecorder
files:
  - filter:
      - out
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  perMachine: false
electronVersion: 29.4.6
